### ISSUE TITLE
cat: output.txt: No such file or directory

### ISSUE THREAD

**Issue by SnigdhaBiswas** [LiberAI/NSpM#44]
On running the ./ask.sh script I'm getting the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/NSpM/nmt/nmt/nmt.py", line 707, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/NSpM/nmt/nmt/nmt.py", line 700, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/content/NSpM/nmt/nmt/nmt.py", line 658, in run_main
    save_hparams=(jobid == 0))
  File "/content/NSpM/nmt/nmt/nmt.py", line 607, in create_or_load_hparams
    hparams = extend_hparams(hparams)
  File "/content/NSpM/nmt/nmt/nmt.py", line 493, in extend_hparams
    unk=vocab_utils.UNK)
  File "/content/NSpM/nmt/nmt/utils/vocab_utils.py", line 137, in check_vocab
    raise ValueError("vocab_file '%s' does not exist." % vocab_file)
ValueError: vocab_file '../data/monument_300/vocab.en' does not exist.
# Job id 0
# Devices visible to TensorFlow: [_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 2340982298104704118), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 7897109989793672363)]
# Creating output directory ../data/monument_300_model ...

ANSWER IN SPARQL SEQUENCE:
cat: output.txt: No such file or directory

Can someone please help me with this?

**Comment by mommi84** [comment]
Can you please share your complete command?
```
ValueError: vocab_file '../data/monument_300/vocab.en' does not exist.
```
This line looks quite self-explanatory.

**Comment by SnigdhaBiswas** [comment]
I used this command. I was following the steps as given in the repository.

./ask.sh data/monument_300 "where is edward vii monument located in?"

**Comment by panchbhai1969** [comment]
Please provide detailed steps to help us recreate the issue you are facing.

Note: `./ask.sh data/monument_300 "where is edward vii monument located in?"`: was this the only command you ran after cloning the repository?
